//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class libro
    {
        public int IdLibro { get; set; }
        public string Libro1 { get; set; }
        public string Editorial { get; set; }
        public string Autor { get; set; }
        public Nullable<int> NumeroPaginas { get; set; }
        public Nullable<int> IdGenero { get; set; }
    
        public virtual Genero Genero { get; set; }
    }
}
